'use client'

import { Bookmark, CloudSun, HeartPulse, MapPin, ShieldCheck } from 'lucide-react'
import type { LocationReading, Pollutant } from './types'
import { colorClasses, formatNumber, formatUpdatedAt } from './types'

export function AQICard({ reading, saved, onSave }: { reading: LocationReading; saved?: boolean; onSave?: () => void }) {
  const name = [reading.location.name, reading.location.region].filter(Boolean).join(', ')
  return <section className="relative overflow-hidden rounded-[24px] bg-[#173f3b] p-6 text-white sm:p-7"><div className="absolute -right-10 -top-16 size-56 rounded-full border border-[#67978a]/25" /><div className="absolute -right-20 -top-24 size-72 rounded-full border border-[#67978a]/15" /><div className="relative flex items-start justify-between"><div><div className="flex items-center gap-2 text-sm text-[#b5d0c5]"><MapPin size={15} /> {name || 'Select a location'} {reading.aqi !== null && <span className="rounded-full bg-[#315b53] px-2 py-0.5 text-[10px] font-medium text-[#d4e8df]">Live</span>}</div><p className="mt-5 text-sm text-[#b5d0c5]">Air Quality Index</p><div className="mt-1 flex items-end gap-3"><span className="text-7xl font-semibold tracking-[-0.08em] text-[#d8f36a]">{reading.aqi ?? '—'}</span><span className="mb-3 text-sm font-medium text-[#c2dad0]">{reading.category ?? 'No reading'}</span></div></div><div className="flex items-start gap-2"><div className="mt-1 grid size-14 place-items-center rounded-2xl bg-[#315b53] text-[#d8f36a]"><CloudSun size={29} strokeWidth={1.5} /></div>{onSave && <button onClick={onSave} disabled={reading.location.latitude === undefined || reading.location.longitude === undefined} aria-label={saved ? 'Location saved' : 'Save location'} className="mt-1 grid size-10 place-items-center rounded-xl bg-[#315b53] text-[#d8f36a] disabled:cursor-not-allowed disabled:opacity-40"><Bookmark size={18} fill={saved ? 'currentColor' : 'none'} /></button>}</div></div><div className="relative mt-6 flex items-center justify-between border-t border-[#3d665d] pt-4 text-xs text-[#b5d0c5]"><span>{formatUpdatedAt(reading.updatedAt)}</span>{reading.category && <span className="flex items-center gap-1.5 text-[#d8f36a]"><ShieldCheck size={14} /> {reading.category === 'Good' ? 'Healthy for most people' : 'Check health guidance'}</span>}</div></section>
}

export function PollutantCard({ item }: { item: Pollutant }) {
  return <article className="rounded-2xl border border-[#dfe9e1] bg-white p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-[#264a44]">{item.name}</span><span className={`size-2 rounded-full ${colorClasses[item.color]}`} /></div><div className="mt-3 flex items-baseline gap-1"><span className="text-2xl font-semibold tracking-[-0.05em] text-[#173f3b]">{formatNumber(item.value)}</span><span className="text-xs text-[#879892]">{item.unit}</span></div><div className="mt-2 flex items-center justify-between"><span className="text-[11px] text-[#879892]">{item.detail}</span><span className="text-[11px] font-semibold text-[#5f9e55]">{item.status ?? 'Pending'}</span></div></article>
}

export function HealthAdvice({ category }: { category: string | null }) {
  const hasReading = Boolean(category)
  return <section className="rounded-[24px] border border-[#dce9db] bg-[#edf6e8] p-5"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#d8edc9] text-[#4e8b50]"><HeartPulse size={20} /></div><div><h3 className="font-semibold text-[#244c42]">{hasReading ? `${category} air for your plans` : 'Health guidance unavailable'}</h3><p className="mt-1 text-sm leading-5 text-[#5b746b]">{hasReading ? 'Guidance will update with the latest local reading.' : 'Choose a location to see actionable guidance for today.'}</p></div></div>{hasReading && <div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/80 px-3 py-1.5 text-xs font-medium text-[#4e7059]">View guidance</span><span className="rounded-full bg-white/80 px-3 py-1.5 text-xs font-medium text-[#4e7059]">Outdoor plans</span></div>}</section>
}

export function StatCard({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-[#dfe9e1] bg-white p-4"><p className="text-xs text-[#879892]">{label}</p><p className="mt-2 text-xl font-semibold text-[#173f3b]">{value}</p></div> }
