'use client'

import { Bookmark, Loader2, MapPin, Trash2 } from 'lucide-react'
import type { SavedLocation } from './types'

type Props = { user: boolean; locations: SavedLocation[]; loading: boolean; error: string; deletingId: string | null; onSelect: (location: SavedLocation) => void; onDelete: (location: SavedLocation) => void; onSignIn: () => void }

export function SavedLocations({ user, locations, loading, error, deletingId, onSelect, onDelete, onSignIn }: Props) {
  return <section className="rounded-[24px] border border-[#dfe9e1] bg-white p-5 sm:p-6">
    <div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-[#173f3b]">Saved locations</h2><p className="mt-1 text-xs text-[#83948d]">Quick access to places you care about</p></div><Bookmark size={18} className="text-[#75ad63]" /></div>
    {!user ? <div className="mt-5 rounded-2xl bg-[#f4f8f2] px-4 py-4"><p className="text-sm font-medium text-[#355c51]">Sign in to save locations</p><p className="mt-1 text-xs leading-5 text-[#83948d]">Your saved places will stay synced across devices.</p><button onClick={onSignIn} className="mt-3 rounded-xl bg-[#173f3b] px-3 py-2 text-xs font-semibold text-white">Sign in</button></div> : loading ? <div className="mt-5 flex items-center gap-2 text-sm text-[#83948d]"><Loader2 className="animate-spin" size={16} /> Loading saved locations…</div> : error ? <p role="alert" className="mt-5 rounded-xl bg-red-50 px-3 py-3 text-xs text-red-700">{error}</p> : locations.length === 0 ? <div className="mt-5 rounded-2xl bg-[#f4f8f2] px-4 py-5 text-center"><MapPin className="mx-auto text-[#75ad63]" size={20} /><p className="mt-2 text-sm font-medium text-[#355c51]">No saved locations yet</p><p className="mt-1 text-xs text-[#83948d]">Use the bookmark on a live reading to add one.</p></div> : <div className="mt-4 flex flex-col gap-2">{locations.map((location) => <div key={location.id} className="flex items-center gap-2 rounded-2xl border border-[#edf2ee] px-3 py-2.5"><button onClick={() => onSelect(location)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[#eff6ee] text-[#75ad63]"><MapPin size={15} /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-[#355c51]">{location.name}</span><span className="block text-[10px] text-[#8a9b93]">{location.latitude.toFixed(3)}, {location.longitude.toFixed(3)}</span></span></button><button onClick={() => onDelete(location)} disabled={deletingId === location.id} aria-label={`Remove ${location.name}`} className="grid size-8 shrink-0 place-items-center rounded-lg text-[#9aa9a2] transition hover:bg-red-50 hover:text-red-600 disabled:opacity-50">{deletingId === location.id ? <Loader2 className="animate-spin" size={15} /> : <Trash2 size={15} />}</button></div>)}</div>}
  </section>
}
