'use client'

import { ChevronDown } from 'lucide-react'
import type { LocationReading } from './types'

export function AQIChart({ trend }: { trend: LocationReading['trend'] }) {
  const points = trend.length > 1 ? trend.map((point, i) => `${(i / (trend.length - 1)) * 100},${100 - Math.min(100, Math.max(0, (point.value / 100) * 100))}`).join(' ') : ''
  return <section className="rounded-[24px] border border-[#dfe9e1] bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><h2 className="font-semibold text-[#173f3b]">Air quality trend</h2><p className="mt-1 text-xs text-[#83948d]">AQI over the selected period</p></div><button className="flex items-center gap-1 rounded-lg bg-[#f0f5ef] px-3 py-2 text-xs font-semibold text-[#4b6e62]">24h <ChevronDown size={13} /></button></div>{trend.length > 1 ? <div className="relative mt-6 h-[180px] overflow-hidden"><div className="absolute inset-0 flex flex-col justify-between text-[10px] text-[#a3b0aa]"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="absolute inset-y-0 left-7 right-0 flex flex-col justify-between"><div className="border-t border-dashed border-[#e6eee8]" /><div className="border-t border-dashed border-[#e6eee8]" /><div className="border-t border-dashed border-[#e6eee8]" /><div className="border-t border-dashed border-[#e6eee8]" /><div className="border-t border-dashed border-[#e6eee8]" /></div><svg className="absolute inset-y-2 left-7 right-0 h-[150px] w-[calc(100%-28px)] overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 100"><polyline points={points} fill="none" stroke="#75ad63" strokeWidth="1.8" vectorEffect="non-scaling-stroke" /></svg><div className="absolute bottom-0 left-7 right-0 flex justify-between text-[10px] text-[#a3b0aa]"><span>{trend[0]?.label}</span><span>{trend[Math.floor(trend.length / 2)]?.label}</span><span>{trend.at(-1)?.label}</span></div></div> : <div className="mt-6 grid h-[180px] place-items-center rounded-2xl bg-[#f5f8f4] text-center text-sm text-[#83948d]">Trend data will appear when the air-quality service responds.</div>}<div className="mt-4 border-t border-[#edf2ee] pt-4 text-xs text-[#71837b]">Live readings are supplied by the configured air-quality provider.</div></section>
}
